interface GitLabComment {
  body: string;
  position?: {
    base_sha: string;
    start_sha: string;
    head_sha: string;
    old_path: string;
    new_path: string;
    position_type: 'text';
    old_line?: number;
    new_line?: number;
  };
}

export class GitLabAPI {
  private static getGitLabInfo() {
    const url = window.location.href;
    const match = url.match(/https?:\/\/([^\/]+)\/([^\/]+)\/([^\/]+)\/-\/merge_requests\/(\d+)/);

    if (!match) {
      throw new Error('Not a GitLab merge request page');
    }

    return {
      baseUrl: `https://${match[1]}`,
      projectPath: `${match[2]}/${match[3]}`,
      mergeRequestId: match[4]
    };
  }

  private static async getGitLabToken(): Promise<string> {
    // Try to get token from extension storage or prompt user
    return new Promise((resolve, reject) => {
      chrome.storage.sync.get(['gitlab_token'], (result) => {
        if (result.gitlab_token) {
          resolve(result.gitlab_token);
        } else {
          // Prompt user for token
          const token = prompt('Please enter your GitLab Personal Access Token (requires api scope):');
          if (token) {
            chrome.storage.sync.set({ gitlab_token: token });
            resolve(token);
          } else {
            reject(new Error('GitLab token required'));
          }
        }
      });
    });
  }

  public static async postCodeSuggestion(
    line: string,
    suggestionTitle: string,
    currentCode: string,
    suggestedCode: string,
    reason: string
  ): Promise<boolean> {
    try {
      const { baseUrl, projectPath, mergeRequestId } = this.getGitLabInfo();
      const token = await this.getGitLabToken();

      // Get merge request details to get the commit SHAs
      const mrResponse = await fetch(
        `${baseUrl}/api/v4/projects/${encodeURIComponent(projectPath)}/merge_requests/${mergeRequestId}`,
        {
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
          }
        }
      );

      if (!mrResponse.ok) {
        throw new Error('Failed to get merge request details');
      }

      const mrData = await mrResponse.json();
      const { diff_refs } = mrData;

      // Create a suggestion comment
      const commentBody = `## 🚀 Code Improvement Suggestion: ${suggestionTitle}

**Current Code (Line ${line}):**
\`\`\`
${currentCode}
\`\`\`

**Suggested Fix:**
\`\`\`suggestion
${suggestedCode}
\`\`\`

**Reason:** ${reason}

---
*Automatically generated by GitLab AI Code Review Tool*`;

      // Post the comment
      const commentResponse = await fetch(
        `${baseUrl}/api/v4/projects/${encodeURIComponent(projectPath)}/merge_requests/${mergeRequestId}/notes`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            body: commentBody
          })
        }
      );

      if (!commentResponse.ok) {
        throw new Error('Failed to post comment');
      }

      return true;
    } catch (error: any) {
      console.error('Error posting to GitLab:', error);
      alert(`Failed to post to GitLab: ${error.message}`);
      return false;
    }
  }

  public static setupGlobalFunction() {
    // Store review data globally for the apply function
    let currentReviewData: any[] = [];

    window.applyCodeSuggestion = async (index: number, line: string) => {
      if (!currentReviewData[index]) {
        alert('Cannot find the corresponding code suggestion');
        return;
      }

      const item = currentReviewData[index];
      const button = document.querySelector(`button[onclick*="${index}"]`) as HTMLButtonElement;

      if (button) {
        button.disabled = true;
        button.innerHTML = '🔄 Posting...';
      }

      try {
        const success = await GitLabAPI.postCodeSuggestion(
          line,
          item.issue || item.title || 'Code Improvement',
          item.current || item.current_code || '',
          item.suggested || item.suggested_code || '',
          item.why || item.reason || 'Code quality improvement'
        );

        if (success) {
          if (button) {
            button.innerHTML = '✅ Posted';
            button.style.background = '#28a745';
          }

          // Show success notification
          const notification = document.createElement('div');
          notification.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            background: #28a745;
            color: white;
            padding: 12px 20px;
            border-radius: 6px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.2);
            z-index: 10000;
            font-family: -apple-system, BlinkMacSystemFont, sans-serif;
          `;
          notification.textContent = '✅ Code suggestion posted to GitLab';
          document.body.appendChild(notification);

          setTimeout(() => {
            notification.remove();
          }, 3000);
        } else {
          if (button) {
            button.disabled = false;
            button.innerHTML = '🚀 Apply to GitLab';
          }
        }
      } catch (error) {
        if (button) {
          button.disabled = false;
          button.innerHTML = '🚀 Apply to GitLab';
        }
      }
    };

    // Function to update current review data
    window.setReviewData = (data: any[]) => {
      currentReviewData = data;
    };
  }
}

// Global type declarations
declare global {
  interface Window {
    applyCodeSuggestion?: (index: number, line: string) => void;
    setReviewData?: (data: any[]) => void;
  }
}
